"""Explore lower-half decompositions generated by the NRCM.

This diagnostic uses the position-coordinate rational Dyck path model from the
Dyck NRCM proof notes.  For a coprime slope r/s, it checks whether the naive
rational cyclic map gives a lower-half decomposition in each low-defect layer:

* every path of defect d and area a < (M-d)/2 has a defined NRCM image;
* the image has the same defect and area a+1;
* the image remains in the lower half;
* the map is injective on the checked lower-half sources.

The theorem in Dyck proves deficit preservation whenever NRCM is defined.  This
script is only testing whether the partial map is sufficiently defined and
injective to give lower-half strings in finite low-defect ranges.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from dataclasses import dataclass
from math import gcd
from typing import Iterable, Sequence


Path = tuple[int, ...]


@dataclass(frozen=True)
class PathData:
    q: Path
    area: int
    defect: int


@dataclass(frozen=True)
class Move:
    k: int
    after: Path


@dataclass(frozen=True)
class Failure:
    defect: int
    area: int
    q: Path
    reason: str


def ceiling_heights(r: int, s: int) -> Path:
    return tuple(r * i // s for i in range(s))


def labels(r: int, s: int) -> Path:
    return tuple((r * i) % s for i in range(s))


def increments(r: int, s: int) -> Path:
    return tuple(r * (i + 1) // s - r * i // s for i in range(s))


def total_degree(r: int, s: int) -> int:
    return sum(ceiling_heights(r, s))


def area(q_values: Sequence[int]) -> int:
    return sum(q_values)


def is_capacity_valid(q_values: Sequence[int], r: int, s: int) -> bool:
    heights = ceiling_heights(r, s)
    return len(q_values) == s and q_values[0] == 0 and all(0 <= q_values[i] <= heights[i] for i in range(s))


def path_heights(q_values: Sequence[int], r: int, s: int) -> Path:
    heights = ceiling_heights(r, s)
    return tuple(heights[i] - q_values[i] for i in range(s))


def is_path_valid(q_values: Sequence[int], r: int, s: int) -> bool:
    if not is_capacity_valid(q_values, r, s):
        return False
    p_values = path_heights(q_values, r, s)
    return all(p_values[i] <= p_values[i + 1] for i in range(s - 1))


def valid_paths(r: int, s: int) -> Iterable[Path]:
    heights = ceiling_heights(r, s)
    p_values = [0] * s

    def rec(index: int, minimum_path_height: int) -> Iterable[Path]:
        if index == s:
            yield tuple(heights[i] - p_values[i] for i in range(s))
            return
        for value in range(minimum_path_height, heights[index] + 1):
            p_values[index] = value
            yield from rec(index + 1, value)

    yield from rec(1, 0)


def suffix_cyclic_candidate(q_values: Sequence[int], r: int, s: int, suffix_start: int) -> Path:
    labs = labels(r, s)
    suffix = list(range(suffix_start, s))
    by_label = sorted(suffix, key=lambda index: labs[index])
    old = {index: q_values[index] for index in suffix}
    out = list(q_values)
    for source, destination in zip(by_label, by_label[1:]):
        out[destination] = old[source]
    out[by_label[0]] = old[by_label[-1]] + 1
    return tuple(out)


def nrcm(q_values: Sequence[int], r: int, s: int) -> Move | None:
    for suffix_start in range(1, s):
        candidate = suffix_cyclic_candidate(q_values, r, s, suffix_start)
        if not is_capacity_valid(candidate, r, s):
            continue
        if is_path_valid(candidate, r, s):
            return Move(suffix_start, candidate)
        return None
    return None


def pair_summand(q_values: Sequence[int], r: int, s: int, i: int, j: int) -> int:
    labs = labels(r, s)
    inc = increments(r, s)
    qi = q_values[i]
    qj = q_values[j]
    u = abs(qi - qj)
    if qi != qj and ((qi > qj) != (labs[i] > labs[j])):
        u -= 1
    u = max(u, 0)
    if qi > qj:
        v = inc[i] - (q_values[i + 1] - q_values[i])
    elif qj > qi:
        v = inc[i - 1] - (q_values[i] - q_values[i - 1])
    else:
        v = 0
    return min(u, v)


def defect(q_values: Sequence[int], r: int, s: int) -> int:
    return sum(pair_summand(q_values, r, s, i, j) for i in range(1, s) for j in range(i + 1, s))


def load_path_data(r: int, s: int, max_defect: int | None) -> tuple[dict[Path, PathData], Counter[int]]:
    records: dict[Path, PathData] = {}
    defect_counts: Counter[int] = Counter()
    for q_values in valid_paths(r, s):
        d = defect(q_values, r, s)
        defect_counts[d] += 1
        if max_defect is None or d <= max_defect:
            records[q_values] = PathData(q_values, area(q_values), d)
    return records, defect_counts


def check_defect_layer(records: dict[Path, PathData], r: int, s: int, d: int) -> tuple[Counter[str], Failure | None]:
    m_value = total_degree(r, s)
    middle = (m_value - d) / 2
    sources = sorted(
        (data for data in records.values() if data.defect == d and 2 * data.area < m_value - d),
        key=lambda data: (data.area, data.q),
    )
    allowed_outputs = {data.q for data in records.values() if data.defect == d and 2 * data.area <= m_value - d + 2}
    owners: dict[Path, Path] = {}
    counts: Counter[str] = Counter()
    counts["sources_below_midline"] = len(sources)
    counts["allowed_outputs"] = len(allowed_outputs)
    for data in sources:
        move = nrcm(data.q, r, s)
        counts["attempts"] += 1
        if move is None:
            return counts, Failure(d, data.area, data.q, "NRCM undefined")
        output = move.after
        output_data = records.get(output)
        if output_data is None:
            return counts, Failure(d, data.area, data.q, f"NRCM output not in retained records: {output}")
        if output_data.defect != d:
            return counts, Failure(d, data.area, data.q, f"defect changed to {output_data.defect}: {output}")
        if output_data.area != data.area + 1:
            return counts, Failure(d, data.area, data.q, f"area changed to {output_data.area}: {output}")
        if output not in allowed_outputs:
            return counts, Failure(d, data.area, data.q, f"output not in next-area target: {output}")
        previous = owners.setdefault(output, data.q)
        if previous != data.q:
            return counts, Failure(d, data.area, data.q, f"non-injective output {output}, previous source {previous}")
        counts["defined_injective_moves"] += 1
        counts[f"suffix_{move.k}"] += 1
    counts["distinct_outputs"] = len(owners)
    return counts, None


def scan_slope(r: int, s: int, max_defect: int | None) -> tuple[list[str], bool]:
    if r <= 0 or s <= 1 or gcd(r, s) != 1:
        raise ValueError("expected a positive coprime slope r/s with s>1")
    records, defect_counts = load_path_data(r, s, max_defect)
    highest = max(defect_counts) if defect_counts else -1
    limit = highest if max_defect is None else min(max_defect, highest)
    lines = [f"slope={r}/{s} M={total_degree(r, s)} retained_paths={len(records)} total_paths={sum(defect_counts.values())}"]
    consecutive_ok = -1
    all_ok = True
    for d in range(limit + 1):
        counts, failure = check_defect_layer(records, r, s, d)
        if failure is None:
            if consecutive_ok == d - 1:
                consecutive_ok = d
            lines.append(
                f"  defc={d}: PASS sources={counts['sources_below_midline']} "
                f"allowed_outputs={counts['allowed_outputs']} moves={counts['defined_injective_moves']}"
            )
            continue
        all_ok = False
        lines.append(
            f"  defc={d}: FAIL sources={counts['sources_below_midline']} "
            f"allowed_outputs={counts['allowed_outputs']} reason={failure.reason} "
            f"area={failure.area} q={failure.q}"
        )
        for later in range(d + 1, limit + 1):
            later_counts, later_failure = check_defect_layer(records, r, s, later)
            status = "PASS" if later_failure is None else "FAIL"
            detail = "" if later_failure is None else f" reason={later_failure.reason} area={later_failure.area} q={later_failure.q}"
            lines.append(
                f"  defc={later}: {status} sources={later_counts['sources_below_midline']} "
                f"allowed_outputs={later_counts['allowed_outputs']}{detail}"
            )
        break
    lines.append(f"  initial_passing_defect_range: 0..{consecutive_ok}" if consecutive_ok >= 0 else "  initial_passing_defect_range: empty")
    return lines, all_ok


def parse_cases(text: str) -> tuple[tuple[int, int], ...]:
    cases: list[tuple[int, int]] = []
    for item in text.split(","):
        item = item.strip()
        if not item:
            continue
        left, right = item.split("/")
        cases.append((int(left), int(right)))
    return tuple(cases)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cases", type=parse_cases, required=True, help="comma-separated slopes, e.g. 7/5,10/7")
    parser.add_argument("--max-defect", type=int, default=20, help="maximum defect layer to test")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    ok = True
    for index, (r, s) in enumerate(args.cases):
        if index:
            print()
        lines, case_ok = scan_slope(r, s, args.max_defect)
        ok = ok and case_ok
        for line in lines:
            print(line)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
